package com.unisys.leida.framework.sharedobjects.client.vo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UpdatedTestFile implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public UpdatedTestFile() {
    }




}