package com.unisys.drools;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	private java.lang.Integer age;

	private Integer salary;


	private String result;


	private java.lang.String quality;

	public Person() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Integer getSalary() {
		return this.salary;
	}

	public void setSalary(java.lang.Integer salary) {
		this.salary = salary;
	}

	public java.lang.String getResult() {
		return this.result;
	}

	public void setResult(java.lang.String result) {
		this.result = result;
	}

	public java.lang.String getQuality() {
		return this.quality;
	}

	public void setQuality(java.lang.String quality) {
		this.quality = quality;
	}

	public Person(java.lang.String name, java.lang.Integer age,
			java.lang.Integer salary, java.lang.String result,
			java.lang.String quality) {
		this.name = name;
		this.age = age;
		this.salary = salary;
		this.result = result;
		this.quality = quality;
	}

}